In [26]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from IPython.display import display

In [27]:
# hitting stats csv
hitting_stats = pd.read_csv("yankees_hitters_21.csv")
hitting_stats.head()

,Player,Team,Pos,Age,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,SH,SF,HBP,AVG,OBP,SLG,OPS
0,DJ LeMahieu,NYY,2B,32,16,65,8,18,4,0,1,5,0,0,8,13,0,0,0,0.277,0.356,0.385,0.741
1,Gleyber Torres,NYY,SS,24,16,59,4,11,2,0,0,1,1,0,9,15,0,0,0,0.186,0.294,0.220,0.514
2,Gio Urshela,NYY,3B,29,16,58,6,16,4,0,2,7,1,0,3,13,0,0,0,0.276,0.311,0.448,0.759
3,Giancarlo Stanton,NYY,DH,31,15,57,5,9,1,0,3,12,0,0,6,21,0,0,0,0.158,0.238,0.333,0.571
4,Aaron Judge,NYY,OF,28,15,56,6,15,1,0,4,8,0,0,8,15,0,0,0,0.268,0.359,0.500,0.859

In [28]:
# list all column headers
list(hitting_stats)

['Player',
 'Team',
 'Pos',
 'Age',
 'G',
 'AB',
 'R',
 'H',
 '2B',
 '3B',
 'HR',
 'RBI',
 'SB',
 'CS',
 'BB',
 'SO',
 'SH',
 'SF',
 'HBP',
 'AVG',
 'OBP',
 'SLG',
 'OPS']

In [29]:
# show dataframe with all columns displayed
pd.options.display.max_columns = None
display(hitting_stats)

,Player,Team,Pos,Age,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,SH,SF,HBP,AVG,OBP,SLG,OPS
0,DJ LeMahieu,NYY,2B,32,16,65,8,18,4,0,1,5,0,0,8,13,0,0,0,0.277,0.356,0.385,0.741
1,Gleyber Torres,NYY,SS,24,16,59,4,11,2,0,0,1,1,0,9,15,0,0,0,0.186,0.294,0.220,0.514
2,Gio Urshela,NYY,3B,29,16,58,6,16,4,0,2,7,1,0,3,13,0,0,0,0.276,0.311,0.448,0.759
3,Giancarlo Stanton,NYY,DH,31,15,57,5,9,1,0,3,12,0,0,6,21,0,0,0,0.158,0.238,0.333,0.571
4,Aaron Judge,NYY,OF,28,15,56,6,15,1,0,4,8,0,0,8,15,0,0,0,0.268,0.359,0.500,0.859
5,Aaron Hicks,NYY,OF,31,15,52,5,8,1,0,1,5,0,0,7,15,0,0,1,0.154,0.267,0.231,0.498
6,Gary Sanchez,NYY,C,28,14,45,6,9,1,0,2,4,0,0,7,12,0,0,1,0.200,0.321,0.356,0.677
7,Clint Frazier,NYY,OF,26,13,40,3,7,2,0,0,1,0,0,5,15,0,0,0,0.175,0.267,0.225,0.492
8,Jay Bruce,NYY,OF,34,10,34,3,4,1,0,1,3,0,0,5,13,0,0,0,0.118,0.231,0.235,0.466
9,Brett Gardner,NYY,OF,37,11,28,4,6,2,0,0,1,0,0,5,9,1,0,0,0.214,0.333,0.286,0.619
10,Rougned Odor,NYY,2B,27,8,25,3,3,0,0,1,3,0,0,1,3,0,0,1,0.120,0.185,0.240,0.425
11,Kyle Higashioka,NYY,C,31,8,13,3,4,1,0,2,4,0,0,3,2,0,0,0,0.308,0.438,0.846,1.284
12,Mike Tauchman,NYY,OF,30,7,9,1,1,0,0,0,0,2,0,0,3,1,0,0,0.111,0.111,0.111,0.222
13,Mike Ford,NYY,1B,28,2,7,0,1,0,0,0,1,0,0,1,1,0,0,0,0.143,0.250,0.143,0.393
14,Tyler Wade,NYY,2B,26,6,3,2,1,0,0,0,0,0,0,0,1,0,0,0,0.333,0.333,0.333,0.666

In [30]:
# group players by position
outfielders = hitting_stats[(hitting_stats["Pos"] == "OF")]
outfielders

,Player,Team,Pos,Age,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,SH,SF,HBP,AVG,OBP,SLG,OPS
4,Aaron Judge,NYY,OF,28,15,56,6,15,1,0,4,8,0,0,8,15,0,0,0,0.268,0.359,0.500,0.859
5,Aaron Hicks,NYY,OF,31,15,52,5,8,1,0,1,5,0,0,7,15,0,0,1,0.154,0.267,0.231,0.498
7,Clint Frazier,NYY,OF,26,13,40,3,7,2,0,0,1,0,0,5,15,0,0,0,0.175,0.267,0.225,0.492
8,Jay Bruce,NYY,OF,34,10,34,3,4,1,0,1,3,0,0,5,13,0,0,0,0.118,0.231,0.235,0.466
9,Brett Gardner,NYY,OF,37,11,28,4,6,2,0,0,1,0,0,5,9,1,0,0,0.214,0.333,0.286,0.619
12,Mike Tauchman,NYY,OF,30,7,9,1,1,0,0,0,0,2,0,0,3,1,0,0,0.111,0.111,0.111,0.222

In [35]:
# group by each infield position
first_baseman = hitting_stats[(hitting_stats["Pos"] == "1B")]
second_baseman = hitting_stats[(hitting_stats["Pos"] == "2B")]
third_baseman = hitting_stats[(hitting_stats["Pos"] == "3B")]
shortstops = hitting_stats[(hitting_stats["Pos"] == "SS")]

In [45]:
# Concatenate frames to create dataframe for infielders
frames = [first_baseman, second_baseman, third_baseman, shortstops]
infielders = pd.concat(frames)
infielders

,Player,Team,Pos,Age,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,SH,SF,HBP,AVG,OBP,SLG,OPS
13,Mike Ford,NYY,1B,28,2,7,0,1,0,0,0,1,0,0,1,1,0,0,0,0.143,0.250,0.143,0.393
0,DJ LeMahieu,NYY,2B,32,16,65,8,18,4,0,1,5,0,0,8,13,0,0,0,0.277,0.356,0.385,0.741
10,Rougned Odor,NYY,2B,27,8,25,3,3,0,0,1,3,0,0,1,3,0,0,1,0.120,0.185,0.240,0.425
14,Tyler Wade,NYY,2B,26,6,3,2,1,0,0,0,0,0,0,0,1,0,0,0,0.333,0.333,0.333,0.666
2,Gio Urshela,NYY,3B,29,16,58,6,16,4,0,2,7,1,0,3,13,0,0,0,0.276,0.311,0.448,0.759
1,Gleyber Torres,NYY,SS,24,16,59,4,11,2,0,0,1,1,0,9,15,0,0,0,0.186,0.294,0.220,0.514